metal-toolbox/flasher

internal/worker/liveness.go, internal/worker/worker.go
=> add worker liveness support for flasher

.github/workflows/release.yml, .goreleaser.yaml, Makefile, cmd/version.go, go.mod, go.sum, internal/version/version.go
- Adds the flasher version command, and exports metrics on it.
```
commit: 2121f02
branch: main
git summary: v0.0.1-dirty
buildDate: 1685457915
version: 
Go version: go1.20.3
bmclib version: v2.0.1-0.20230426154556-8907c8d39762
serverservice version: v0.15.3-0.20230519171430-6d4a327f68f3
```
- Adds a Goreleaser configuration, updates CI deps.
=> Add version command and Goreleaser configuration

.goreleaser.yaml
=> .goreleaser: fix dumb copy paste

internal/store/serverservice.go, internal/worker/kv_status.go, internal/worker/worker.go
This makes a few modifications based on integration testing last week with status-KV functionality.
=> fix-up some flasher inconsistencies with status KV

Makefile
=> Makefile: update local devel repository port

cmd/run.go, internal/app/config.go, internal/worker/kv_status.go
=> Require facility code for use-kv

.github/workflows/release.yml
=> ci: update dep and goreleaser build param

.github/workflows/release.yml, .goreleaser.yaml
=> Goreleaser fixes

internal/metrics/metrics.go, internal/worker/kv_status.go, internal/worker/worker.go
=> add some NATS metrics to flasher

internal/outofband/bmc_helpers.go
=> bump logging detail on bmc login failures

internal/worker/liveness.go
Analogous to https://github.com/metal-toolbox/conditionorc/pull/72, this change makes flasher re-register its worker id with NATS if it runs into issues updating its liveness.
=> re-register the worker on checkin failure

internal/outofband/action_handlers.go, internal/outofband/download.go, internal/outofband/download_test.go
- Determines checksum type based on the prefix value, when available
=> outofband/download: determine checksum based on prefix value

internal/model/component.go, internal/outofband/action_handlers.go
=> Disable vendor check

internal/model/task.go, internal/model/task_test.go
=> cap status history at last 5 entries

go.mod, go.sum
Updates bmclib to current release
=> Go: update bmclib to v2.2.1

internal/outofband/action_handlers.go
- Slightly improved error return and log
- Additional polling for installed firmware verify
=> Poll inventory attempts

go.mod, go.sum, internal/store/fleetdb.go, internal/store/fleetdb_attrs.go
=> Update rivets to include nil pointer deref fix

internal/outofband/action_handlers.go
This fixes the poller failure when comparing the installed firmware with the expected for BMC firmware - for firmware upload verify tasks.
The poller is invoked for both install and firmware upload verify tasks, it did not differentiate between the two before attempting to collect inventory from the BMC to verify the installed firmware matches the expected. When polling a firmware upload, verify task - an inventory and version comparison is not required, since at this point the install is yet to be done.
=> outofband: poller to not collect inventory for upload verify tasks

internal/install/install.go, internal/install/task_handler.go, internal/model/action.go, internal/outofband/action_handlers.go, internal/outofband/actions.go, internal/outofband/actions_test.go, internal/outofband/bmc_helpers.go
Fixes the powerOff step from being skipped, since the provider install parameter was not considered.
=> outofband: power off the host if the provider indicates its required

go.mod, go.sum
=> update bmclib for Supermicro x12spo-ntf BIOS update fixes

internal/worker/worker.go
=> Remove unused variable

cmd/run.go, go.mod, go.sum, internal/app/config.go
=> Purge duplicate token field

go.mod, go.sum
This version includes a fix that will have flasher inband exit cleanly if theres nothing for it to do.
=> go: update ctrl lib

go.mod, go.sum
=> FS-1920; Bump tag

.golangci.yml, internal/install/task_handler.go
=> Fix providing models in models, not vendor
